{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "d3a92551_696fa7e6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 511
      },
      "writtenOn": "2022-02-23T14:39:59Z",
      "side": 1,
      "message": "recheck",
      "revId": "2bf5d8f7024603ce688ca45bcd18426fa9b766c1",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2022ad2e_7a255912",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 511
      },
      "writtenOn": "2022-02-23T14:41:18Z",
      "side": 1,
      "message": "This seems downright bizarre, since the requirements, nor the reported change modified the requirements nor even touched the failed test. I\u0027m unable to reproduce the failed test locally as well, so hopefully this will just clear itself up",
      "revId": "2bf5d8f7024603ce688ca45bcd18426fa9b766c1",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}